[project]
name = "readme-template"
version = "0.1.0"
description = "Render template readme in multiple languages"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
]
